app/blueprints/blogs/views.py
from flask import request, render_template, jsonify, url_for, redirect, flash, current_app, Blueprint
from flask_login import login_required
from app.app import db, secure_filename
from slugify import slugify
import logging, os, markdown
from app.models import Blog, BlogMedia


blog_blueprint = Blueprint("blogs", __name__, template_folder='templates')


@blog_blueprint.route('/add_blog', methods=['POST'])
@login_required
def add_blog():
    try:
        # Get the form data
        title = request.form.get('title')
        content = request.form.get('content')

        # Validate the inputs
        if not title or not content:
            flash('Title and content are required', 'danger')
            return redirect(url_for('admin.dashboard') + "#blog")

        # Generate a unique slug based on the title
        slug = slugify(title)
        
        # Ensure the slug is unique
        existing_blog = Blog.query.filter_by(slug=slug).first()
        if existing_blog:
            flash('A blog with this title already exists. Please choose a different title.', 'danger')
            return redirect(url_for('admin.dashboard') + "#blog")

        # Save the new blog to the database
        new_blog = Blog(title=title, content=content, slug=slug)
        db.session.add(new_blog)
        db.session.flush()  # This assigns an ID to new_blog without committing the transaction

        # Handle the uploaded images (if any)
        images = request.files.getlist('images[]')
        for image in images:
            if image and image.filename != '':
                filename = secure_filename(image.filename)
                image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                image.save(image_path)
                
                # Save image info to BlogMedia table
                blog_media = BlogMedia(filename=filename, blog_id=new_blog.blog_id)
                db.session.add(blog_media)

        # Commit everything to the database
        db.session.commit()
        flash('Blog added successfully!', 'success')
        return redirect(url_for('admin.dashboard') + "#blog")
    
    except Exception as e:
        db.session.rollback()  # Rollback the transaction on error
        flash(f'Error: {str(e)}', 'danger')
        print(f'Error: {str(e)}')
        return redirect(url_for('admin.dashboard') + "#blog")
    
    

@blog_blueprint.route('/edit_blog/<int:blog_id>', methods=['POST'])
@login_required
def edit_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    
    # Get content from the form
    title = request.form.get('title')
    content = request.form.get('content')

    # Convert Markdown to HTML
    
    # Update title and content
    blog.title = title
    blog.content = content
    blog.slug = slugify(blog.title)

    # Handle the uploaded images (if any)
    images = request.files.getlist('images[]')
    for image in images:
        if image and image.filename != '':
            filename = secure_filename(image.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(image_path)
            blog_media = BlogMedia(filename=filename, blog_id=blog_id)
            db.session.add(blog_media)
                
    try:
        db.session.commit()
        # flash('Blog updated successfully!', 'success')
        flash( 'Blog updated successfully', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error updating blog: {str(e)}', 'success')


    return redirect(url_for('admin.dashboard') + '#blogs')

@blog_blueprint.route('/api/get_blog_details', methods=['GET'])
def get_blog_details():
    blog_id = request.args.get('blog_id')
    if not blog_id:
        return jsonify({'success': False, 'message': 'Blog ID is required'}), 400
    
    blog = Blog.query.get(blog_id)
    if not blog:
        return jsonify({'success': False, 'message': 'Blog not found'}), 404
    
    # Return the blog details in a JSON response
    return jsonify({
        'success': True,
        'data': {
            'blog_id': blog.blog_id,
            'title': blog.title,
            'content': blog.content,
            'first_image': blog.first_image_path  # Assuming first_image_path is a property
        }
    }), 200


@blog_blueprint.route('/delete_blog_image/<int:image_id>', methods=['POST'])
def delete_blog_image(image_id):
    image = BlogMedia.query.get_or_404(image_id)
    db.session.delete(image)
    db.session.commit()
    flash('Blog successfully deleted!', 'success')

    return redirect(url_for('admin.dashboard') + '#blog' )


@blog_blueprint.route('/blog-details/<int:blog_id>')
def blog_details(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    return render_template('blogs/blog_details.html', blog=blog)

@blog_blueprint.route('/blogs')
def blogs():
    blogs = Blog.query.all()
    return render_template('blogs/blogs.html', blogs=blogs)


@blog_blueprint.route('/delete-edit-blog-image', methods=['POST'])
@login_required
def delete_edit_blog_image():
    data = request.get_json()  # Get the JSON data from the request body
    image_id = data.get('image_id')
    image_path = data.get('image_path')

    image = BlogMedia.query.get(image_id)
    if image:
        try:
            os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], image_path))
        except FileNotFoundError:
            flash(f"File {image_path} not found", 'error')
        # Delete the image from the database
        db.session.delete(image)
        db.session.commit()
        flash('Image deleted successfully', 'success')
    else:
        flash('Failed to delete image', 'error')

    return redirect(url_for('admin.dashboard') + '#blog')




@blog_blueprint.route('/delete_blog/<int:blog_id>', methods=['POST'])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    
    # Fetch the associated images
    if blog.images:
        for image in blog.images:
            # Construct the image path
            image_filename = secure_filename(image.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], image_filename)
            
            # Remove the image file from the upload folder if it exists
            if os.path.exists(image_path) and os.path.isfile(image_path):
                try:
                    os.remove(image_path)
                except OSError as e:
                    flash(f"Error deleting image file: {e}", "error")
            
            # Remove the image record
            db.session.delete(image)
    
    # Delete the blog post itself
    db.session.delete(blog)
    
    try:
        db.session.commit()
        flash("Blog post and images deleted successfully!", "success")
    except Exception as e:
        db.session.rollback()
        flash(f"An error occurred while deleting the blog post: {str(e)}", "danger")
    
    return redirect(url_for('admin.dashboard') + "#blog")

app/blueprints/blogs/templates/blogs/blog_details.html
{% extends "base.html" %} 
{% block head %} 
    {% block title %} 
        Blogs Page 
    {%endblock %} 
    {% include "sweetalerts.html" %} 
    {% include "others_header.html" %}
    <link rel="stylesheet" href="{{ url_for('static', filename='header.css') }}" />

    <link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet">

    <!-- Code highlighter -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>
{% endblock %}

{% block content %}
  <style>
    .markdown-content img {
      width: 80%;
      display: block;
    }

    .carousel-inner {
      background: white;
      border-radius: 10px;
      
    }
    
    .carousel-control-prev,
    .carousel-control-next {
        text-decoration: none;
        margin-top: 150px; 
        width: 50px;
        height: 50px;
        border-radius: 10%;
        background-color: #333333;
        color: #fff;
        opacity: 0.9;
        transition: opacity 0.3s;
    }
  
    .carousel-control-prev:hover,
    .carousel-control-next:hover {
        opacity: 1;
    }

    .carousel-control-prev i,
    .carousel-control-next i {
        font-size: 20px;
    }

    .description {
        color: black !important;
    }

    .view-container {
        margin-top: 150px;
    }
  
    p {
        color: #000 !important;
        font-size: 20px !important;
    }

    .blog_img {
      width: auto;
      height: 550px;
      max-height: 550px;
      object-fit: cover;
      object-position: center;
    }

    .admin__btn {
      color: #fff !important;
    }
  </style>

    <section class="blog_section mt-5 pt-5">
      <div class="container mt-5">
        <h1 class="blog_title">{{ blog.title }}</h1>
        <div class="Blog_Card">
          {% if blog.images %}
          <div id="blogCarousel" class="carousel slide" data-bs-interval="false">
            <div class="carousel-inner">
              <div class="img_container">
                {% for image in blog.images %}
                  <div
                    class="carousel-item {% if loop.index == 1 %}active{% endif %}"
                  >
                  <img
                    src="{{ url_for('static', filename='uploads/' ~ image.filename) }}"
                    class="d-block w-100 blog_img"
                    alt="..."
                  />
                </div>
                {% endfor %}
              </div>
            </div>
            <a
              class="carousel-control-prev"
              href="#blogCarousel"
              role="button"
              data-slide="prev"
            >
              <span
                class="carousel-control-prev-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only"></span>
            </a>
            <a
              class="carousel-control-next"
              href="#blogCarousel"
              role="button"
              data-slide="next"
            >
              <span
                class="carousel-control-next-icon"
                aria-hidden="true"
              ></span>
              <span class="sr-only"></span>
            </a>
          </div>
          {% endif %}
        </div>

        <div class="blog-content">
          <p class="blog_content">
            <div class="container markdown-content">
              {{ blog.content | markdown | safe }}
            </div>
            
          </p>
        </div>

        <!-- <p class="blog_content">{{ blog.content }}</p> -->
      </div>
    </section>

{% endblock %}


{% block scripts %}
    <!-- jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

    <script>
      document.querySelectorAll('.markdown-content a').forEach(function(anchor) {
        anchor.setAttribute('target', '_blank');
    });

    </script>
{% endblock %}

app/blueprints/blogs/templates/blogs/blogs.html
{% extends "base.html" %} {% block head %} {% block title %} Blogs Page
{%endblock %} {% include "sweetalerts.html" %} {% include "others_header.html"%}

<!-- Sweet alert Js -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- Bootstrap Links -->
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
  crossorigin="anonymous"
/>

<!-- JQuery Link -->
<script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"
></script>

<!-- Bootstrap Icons -->
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
{% endblock %} {% block content %}

<section class="blog_section mt-5 pt-5">
  <div class="container">
    <div class="section__container">
      <div class="blog__container">
        {% for blog in blogs %}
        <div class="blog__card">
          <img
            src="{{ url_for('static', filename='uploads/' ~ blog.first_image_path) if blog.first_image_path else 'static/images/default-image.jpg' }}"
            alt="{{ blog.title }}"
          />
          <div class="text-box" style="bottom: 75%">
            <a
              class="blog_title"
              href="{{ url_for('blogs.blog_details', blog_id=blog.blog_id) }}"
            >
              {% if blog.title|length > 200 %} {{ blog.title[:200] }} {% else %}
              {{ blog.title }} {% endif %}
            </a>
            {% if current_user.is_admin%}
            <div class="edit_or_delete d-flex mt-5 pt-5">
              <span
                style="
                  background: #3498db;
                  padding: 5px 20px;
                  border-radius: 50%;
                  color: #ffffff;
                  cursor: pointer;
                "
                class="icon edit"
                data-bs-toggle="modal"
                data-bs-target="#editBlogModal-{{ blog.blog_id }}"
              >
                <i class="bi bi-pen"></i>
              </span>
              <form
                method="POST"
                id="deleteBlogForm-{{ blog.blog_id }}"
                action="{{ url_for('blogs.delete_blog', blog_id=blog.blog_id) }}"
                style="display: inline"
              >
                <button
                  style="
                    color: #ffffff;
                    padding: 5px 20px;
                    border-radius: 50%;
                    background: rgb(112, 4, 4);
                    cursor: pointer;
                  "
                  type="button"
                  class="icon delete"
                  onclick="confirmDeleteBlog('{{ blog.blog_id }}')"
                >
                  <i class="bi bi-trash"></i>
                </button>
              </form>
            </div>
          </div>
          {% else %}
          <div></div>
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <!-- Edit Blog Modal -->
      {% for blog in blogs %}
      <div
        class="modal fade"
        id="editBlogModal-{{ blog.blog_id }}"
        tabindex="-1"
        aria-labelledby="editBlogModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editBlogModalLabel">Edit Blog</h5>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div class="modal-body">
              <form
                id="editBlogForm-{{ blog.blog_id }}"
                method="POST"
                action="{{ url_for('blogs.edit_blog', blog_id=blog.blog_id) }}"
                enctype="multipart/form-data"
              >
                <input
                  type="hidden"
                  name="blog_id"
                  value="{{ blog.blog_id }}"
                />

                <div class="mb-3">
                  <label
                    for="editBlogTitle-{{ blog.blog_id }}"
                    class="form-label"
                    >Title</label
                  >
                  <input
                    type="text"
                    class="form-control"
                    id="editBlogTitle-{{ blog.blog_id }}"
                    name="title"
                    value="{{ blog.title }}"
                    required
                  />
                </div>

                <div class="mb-3">
                  <label
                    for="editBlogContent-{{ blog.blog_id }}"
                    class="form-label markdown-editor"
                    >Content</label
                  >
                  <textarea
                    class="form-control markdown-editor"
                    id="editBlogContent"
                    name="content"
                    rows="10"
                  >
{{ blog.content }}</textarea
                  >
                </div>

                <div class="mb-3">
                  <label class="form-label">Current Images</label>
                  <div
                    id="editBlogImages-{{ blog.blog_id }}"
                    class="edit__blog-existing-images"
                  >
                    {% for image in blog.images %}
                    <div
                      class="image-container"
                      data-image-id="{{ image.blog_media_id }}"
                    >
                      <img
                        src="{{ url_for('static', filename='uploads/' ~ image.filename) }}"
                        alt="Blog Image"
                        class="img-thumbnail"
                        style="max-width: 150px; max-height: 100px"
                      />
                      <button
                        type="button"
                        class="btn btn-danger btn-sm ms-2 img_del_btn"
                        onclick="deleteEditBlogImage({{ image.blog_media_id }}, '{{ image.filename }}')"
                      >
                        Delete
                      </button>
                    </div>
                    {% endfor %}
                  </div>
                </div>

                <div class="mb-3">
                  <label
                    for="newBlogImages-{{ blog.blog_id }}"
                    class="form-label"
                    >Add New Images</label
                  >
                  <input
                    type="file"
                    class="form-control"
                    id="newBlogImages-{{ blog.blog_id }}"
                    name="images[]"
                    accept="image/*"
                    multiple
                  />
                </div>

                <button type="submit" class="btn btn-primary">
                  Save Changes
                </button>
                <button
                  type="button"
                  class="btn btn-secondary"
                  data-bs-dismiss="modal"
                >
                  Close
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<style>
  a:hover {
    color: blue;
  }

  a {
    text-decoration: none;
  }

  .edit_or_delete {
    margin-top: 85px !important;
  }
</style>
{% endblock %} {% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

<!-- BOOTSTRAP CDN LINK -->

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
  crossorigin="anonymous"
></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
<!-- Bootstrap Bundle with Popper -->
<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
></script>

<script
  integrity="sha384-MrcW6ZMFYlXZ
            *zcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css"
/>
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

{% endblock %}