app/blueprints/blogs/views.py
from flask import request, render_template, jsonify, url_for, redirect, flash, current_app, Blueprint
from flask_login import login_required
from app.app import db, secure_filename
from slugify import slugify
import logging, os, markdown
from app.models import Blog, BlogMedia


blog_blueprint = Blueprint("blogs", __name__, template_folder='templates')


@blog_blueprint.route('/add_blog', methods=['POST'])
@login_required
def add_blog():
    try:
        # Get the form data
        title = request.form.get('title')
        content = request.form.get('content')

        # Validate the inputs
        if not title or not content:
            flash('Title and content are required', 'danger')
            return redirect(url_for('admin.dashboard') + "#blog")

        # Generate a unique slug based on the title
        slug = slugify(title)
        
        # Ensure the slug is unique
        existing_blog = Blog.query.filter_by(slug=slug).first()
        if existing_blog:
            flash('A blog with this title already exists. Please choose a different title.', 'danger')
            return redirect(url_for('admin.dashboard') + "#blog")

        # Save the new blog to the database
        new_blog = Blog(title=title, content=content, slug=slug)
        db.session.add(new_blog)
        db.session.flush()  # This assigns an ID to new_blog without committing the transaction

        # Handle the uploaded images (if any)
        images = request.files.getlist('images[]')
        for image in images:
            if image and image.filename != '':
                filename = secure_filename(image.filename)
                image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                image.save(image_path)
                
                # Save image info to BlogMedia table
                blog_media = BlogMedia(filename=filename, blog_id=new_blog.blog_id)
                db.session.add(blog_media)

        # Commit everything to the database
        db.session.commit()
        flash('Blog added successfully!', 'success')
        return redirect(url_for('admin.dashboard') + "#blog")
    
    except Exception as e:
        db.session.rollback()  # Rollback the transaction on error
        flash(f'Error: {str(e)}', 'danger')
        print(f'Error: {str(e)}')
        return redirect(url_for('admin.dashboard') + "#blog")
    
    

@blog_blueprint.route('/edit_blog/<int:blog_id>', methods=['POST'])
@login_required
def edit_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    
    # Get content from the form
    title = request.form.get('title')
    content = request.form.get('content')

    # Convert Markdown to HTML
    
    # Update title and content
    blog.title = title
    blog.content = content
    blog.slug = slugify(blog.title)

    # Handle the uploaded images (if any)
    images = request.files.getlist('images[]')
    for image in images:
        if image and image.filename != '':
            filename = secure_filename(image.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(image_path)
            blog_media = BlogMedia(filename=filename, blog_id=blog_id)
            db.session.add(blog_media)
                
    try:
        db.session.commit()
        # flash('Blog updated successfully!', 'success')
        flash( 'Blog updated successfully', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error updating blog: {str(e)}', 'success')


    return redirect(url_for('admin.dashboard') + '#blogs')

@blog_blueprint.route('/api/get_blog_details', methods=['GET'])
def get_blog_details():
    blog_id = request.args.get('blog_id')
    if not blog_id:
        return jsonify({'success': False, 'message': 'Blog ID is required'}), 400
    
    blog = Blog.query.get(blog_id)
    if not blog:
        return jsonify({'success': False, 'message': 'Blog not found'}), 404
    
    # Return the blog details in a JSON response
    return jsonify({
        'success': True,
        'data': {
            'blog_id': blog.blog_id,
            'title': blog.title,
            'content': blog.content,
            'first_image': blog.first_image_path  # Assuming first_image_path is a property
        }
    }), 200


@blog_blueprint.route('/delete_blog_image/<int:image_id>', methods=['POST'])
def delete_blog_image(image_id):
    image = BlogMedia.query.get_or_404(image_id)
    db.session.delete(image)
    db.session.commit()
    flash('Blog successfully deleted!', 'success')

    return redirect(url_for('admin.dashboard') + '#blog' )


@blog_blueprint.route('/blog-details/<int:blog_id>')
def blog_details(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    return render_template('blogs/blog_details.html', blog=blog)

@blog_blueprint.route('/blogs')
def blogs():
    blogs = Blog.query.all()
    return render_template('blogs/blogs.html', blogs=blogs)


@blog_blueprint.route('/delete-edit-blog-image', methods=['POST'])
@login_required
def delete_edit_blog_image():
    data = request.get_json()  # Get the JSON data from the request body
    image_id = data.get('image_id')
    image_path = data.get('image_path')

    image = BlogMedia.query.get(image_id)
    if image:
        try:
            os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], image_path))
        except FileNotFoundError:
            flash(f"File {image_path} not found", 'error')
        # Delete the image from the database
        db.session.delete(image)
        db.session.commit()
        flash('Image deleted successfully', 'success')
    else:
        flash('Failed to delete image', 'error')

    return redirect(url_for('admin.dashboard') + '#blog')




@blog_blueprint.route('/delete_blog/<int:blog_id>', methods=['POST'])
@login_required
def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    
    # Fetch the associated images
    if blog.images:
        for image in blog.images:
            # Construct the image path
            image_filename = secure_filename(image.filename)
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], image_filename)
            
            # Remove the image file from the upload folder if it exists
            if os.path.exists(image_path) and os.path.isfile(image_path):
                try:
                    os.remove(image_path)
                except OSError as e:
                    flash(f"Error deleting image file: {e}", "error")
            
            # Remove the image record
            db.session.delete(image)
    
    # Delete the blog post itself
    db.session.delete(blog)
    
    try:
        db.session.commit()
        flash("Blog post and images deleted successfully!", "success")
    except Exception as e:
        db.session.rollback()
        flash(f"An error occurred while deleting the blog post: {str(e)}", "danger")
    
    return redirect(url_for('admin.dashboard') + "#blog")

app/blueprints/home/views.py
from flask import render_template, Blueprint
from app.models import User, Partner, Portfolio, VideoURL, CaseStudy, Blog, Testimonial



home_blueprint = Blueprint('home', __name__, template_folder='templates')


@home_blueprint.route('/')
def index():
    # users = User.query.all()
    partners = Partner.query.all()
    portfolio_items = Portfolio.query.all()
    video = VideoURL.query.first()
    case_studies = CaseStudy.query.all()
    blogs = Blog.query.all()

    testimonials = Testimonial.query.all()
    return render_template('home/index.html', partners=partners, portfolio=portfolio_items, video=video, case_studies=case_studies, blogs=blogs, testimonials=testimonials)

app/blueprints/users/views.py
from flask import render_template, redirect, request, url_for, flash, Blueprint
from app.app import db, login_manager,login_required, login_user, logout_user, current_user, app, generate_token, confirm_token, send_email, salt_key
from app.models import User, Partner, Portfolio, Testimonial, Blog, VideoURL, CaseStudy
from werkzeug.security import generate_password_hash, check_password_hash

user_blueprint = Blueprint("users", __name__, template_folder='templates')


@user_blueprint.route('/all_users')
def all_users():
    return "Here is a list of all Users"


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('users.login'))

@user_blueprint.route('/loginpage')
def login_page():
    return render_template('users/login.html')

@user_blueprint.route('/signup')
def signup():
    return render_template('users/register.html')

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



# @user_blueprint.route('/register', methods=['GET', 'POST'])
# def register():
#     if request.method == 'POST':
#         username = request.form.get('username')
#         email = request.form.get('email')
#         password = generate_password_hash(request.form.get('password'))
#         email_found = User.query.filter((User.email == username)).first()
#         username_found = User.query.filter((User.username == username)).first()
        
#         if email_found:
#             flash("Sorry email already exits try another email", "warning")
            
#         elif username_found:
#             flash("Sorry username already exits try another username", "warning")
         
#         else:      
#             # Assuming you have a way to determine if the user should be an admin
#             # is_admin = True if username == 'Engineer Alison' or email == 'engralison@admin.com' else False
#             user = User(username=username, email=email, password=password)
#             db.session.add(user)
#             db.session.commit()
#             flash('Registration successful! Please log in.', 'success')
#             return redirect(url_for('users.login'))
#     return render_template('users/register.html')



# @user_blueprint.route('/login', methods=['GET', 'POST'])
# def login():
#     if request.method == 'POST':
#         login_credential = request.form.get('username')  # This field will accept both username and email
#         password = request.form.get('password')
#         username = request.form.get('username') 
        
#         # Query the user by username or email
#         user = User.query.filter(
#             (User.username == login_credential) | (User.email == login_credential)
#         ).first()
        
#         if user and check_password_hash(user.password, password):
#             login_user(user)
            
#             if user.is_admin:
#                 flash(f'Login successful! \nWelcome admin {username}', 'success')
#                 return redirect(url_for('admin.dashboard'))
                
#             else:
#                 flash(f'Login successful!\n Welcome {username}', 'success')
#                 return redirect(url_for('home.index'))
                
#         else:
#             flash('Login Unsuccessful. Please check username/email and password and try again!', 'warning')
    
#     return render_template('users/login.html')



@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')

        # Validate inputs
        if not username or not email or not password:
            flash("All fields are required.", "warning")
            return redirect(url_for('users.register'))

        # Check if email or username already exists
        email_found = User.query.filter_by(email=email).first()
        username_found = User.query.filter_by(username=username).first()
        
        if email_found:
            flash("Email already exists. Please use another email.", "warning")
            return redirect(url_for('users.register'))
        elif username_found:
            flash("Username already exists. Please use another username.", "warning")
            return redirect(url_for('users.register'))

        # Create user
        hashed_password = generate_password_hash(password)
        new_user = User(username=username, email=email, password=hashed_password, position="user", role="user")
        db.session.add(new_user)
        db.session.commit()

        # Generate verification token
        token = generate_token(new_user.email)
        confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
        html = render_template("accounts/confirm_email.html", new_user=new_user, confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(new_user.email, subject, html)

        flash("A verification email has been sent. Please check your email.", "info")
        return redirect(url_for('users.inactive'))

    return render_template('users/register.html')


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login_credential = request.form.get('username')  # Accept both username and email
        password = request.form.get('password')

        # Query the user by username or email
        user = User.query.filter(
            (User.username == login_credential) | (User.email == login_credential)
        ).first()
        
        if user and check_password_hash(user.password, password):
            if user.is_active:  # Ensure user is active
                login_user(user)

                if not user.is_confirmed:  # Redirect unconfirmed users to the inactive page
                    flash("Please confirm your account.", "warning")
                    return redirect(url_for('users.inactive'))

                # Successful login
                if user.is_admin:
                    flash(f'Login successful! \nWelcome admin {user.username}!', 'success')
                    return redirect(url_for('admin.dashboard'))
                    
                else:
                    flash(f'Login successful!\n Welcome {user.username}!', 'success')
                    return redirect(url_for('home.index'))
                
            else:
                flash("Your account is inactive. Please contact support.", "danger")
        else:
            flash("Invalid username/email or password.", "danger")

    return render_template('users/login.html')



@user_blueprint.route('/inactive')
def inactive():
    return render_template('accounts/inactive.html')



@user_blueprint.route("/resend")
@login_required
def user_resend_confirmation():
    return redirect(url_for("accounts.resend_confirmation"))


@user_blueprint.route('/verify_email/<token>')
def user_verify_email(token):
    return redirect(url_for("accounts.verify_email", token=token))

app/templates/adminheader.html
{% extends "base.html" %} {% block content %}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid pl-2 pb-0 pt-0">
    <a class="navbar-brand" href="{{ url_for('home.index') }}">ASTRUCT</a>
    

    <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul
        class="navbar-nav me-auto mb-2 mb-lg-0"
      >
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{ url_for('home.index')}}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#partner">partner</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#portfolio">Portfolio</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#caseStudies">casestudies</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#blog">Blog</a>
        </li>
        

        <li class="nav-item">
          <a class="nav-link" href="#testimonials">Testimonials</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#users">Users</a>
        </li>
      </ul>

      <!-- Move Logout link here with ms-auto to push it to the right -->
      <ul class="navbar-nav ms-auto">
        <li class="nav-item d-flex mr-2 back__btn" style="margin-right: 12px !important;">
          <span class="icon p-0" style="margin-top: 12px; font-size: 11px"
            ><i class="bi bi-chevron-left"></i
          ></span>
          <a
            class="nav-link text-warning p-0 pr-3"
            style="margin-top: 4px"
            href="{{ url_for('home.index') }}"
            >Back</a
          >
        </li>

        <li class="nav-item ml-2">
          <a
            href="{{ url_for('users.logout') }}"
            class="nav-link pt-1 pb-1 pl-2 pr-2 mt-1 text-white logout__btn"
            style="background-color: red; border-radius: 50px; font-size: 16px"
            >Logout</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>
        {% block title %} ASTRUCTS {% endblock %}
      </title>

      <!-- Code highlighter -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github-dark.min.css">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
      <script>hljs.highlightAll();</script>


      <!-- CSS Links -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
      <!-- Bootstrap Links -->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
      <!-- Bootstrap Icons -->
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
      />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />


      <link
        rel="stylesheet"
        href="https://unpkg.com/swiper/swiper-bundle.min.css"
      />
      <link rel="stylesheet" href="https://upkg.com/swiper/swiper-bundle.min.css"> 
      <!-- Google fonts -->
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Alkatra:wght@400;500;600;700&family=Dancing+Script:wght@400..700&family=Lato:ital,wght@0,400;0,700;0,900;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Oswald:wght@200..700&family=Roboto+Condensed:ital,wght@0,400;0,700;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Sacramento&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://db.onlinewebfonts.com/c/c2c53906d03ac20447dfd4da50900e82?family=Garamont+AMSTERDAM+Italic"
        rel="stylesheet"
      />

      <!-- Include SimpleMDE nad SweetAlert CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
      
      <!-- SimpleMDE CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
      



      <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      
      <!-- JQuery Link -->
      <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
        crossorigin="anonymous"></script>
    {% endblock %}
  </head>
  <body>

    {% include 'sweetalerts.html' %}

    {% block content %}  {% endblock %}

    {% block scripts %}
      <script integrity="sha384-MrcW6ZMFYlXZ
            *zcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>

      <!-- SWIPER JS CODE -->
      <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
      <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
      <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

      <!-- SimpleMDE JS -->
      <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
      
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
      <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    {% endblock %}

  </body>
</html>

app/templates/header.html
{% extends "base.html" %} {% block content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/header.css') }}"
/>

<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ASTRUCT</a>
    <!-- <button
      class="navbar-toggler collapsed"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button> -->
    <button
      class="navbar-toggler collapsed"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link about-link" href="#about">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#services">Services</a>
        </li>
        <li
          class="nav-item dropdown nav-dropdown-link"
          aria-labelledby="navbarDropdown"
        >
          <a
            class="dropdown-toggle text-color"
            id="dropdownMenu"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            others
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#HowWeWork">How we work</a></li>
            <li><a class="dropdown-item" href="#gallery">Gallery</a></li>
            <li><a class="dropdown-item" href="#video">Video showcase</a></li>
            <li>
              <a class="dropdown-item" href="#casestudies">Case studies</a>
            </li>
            <li>
              <a class="dropdown-item" href="#whychoose">why choose Us?</a>
            </li>
            <li><a class="dropdown-item" href="#reviews">Testimonials</a></li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li><a class="dropdown-item" href="#FAQs">FAQS</a></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="#portfolio">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#blog">Blogs</a>
        </li>
        <li class="nav-item">
          <div class="admin">
            {% if current_user.is_authenticated %} {% if current_user.is_admin
            %}
            <a
              href="{{ url_for('admin.dashboard') }}"
              class="nav-link admin__btn"
              >Dashboard</a
            >
            {% else %}
            <a href="{{ url_for('users.logout') }}" class="nav-link admin__btn"
              >Logout</a
            >
            {% endif %} {% else %}
            <a href="{{ url_for('users.login') }}" class="nav-link admin__btn"
              >LogIn / <span class="text-warning">signUp</span></a
            >
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock %}


{% block scripts %}

<script src="{{ url_for('static', filename='js/script.js') }}"></script>

{% endblock %}

app/templates/others_header.html
{% extends "base.html" %} {% block head %} {% include "sweetalerts.html" %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/others_header.css') }}"
/>
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  rel="stylesheet"
/>

{% endblock %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid pl-2 pb-0 pt-0">
    <a class="navbar-brand" href="#">ASTRUCT</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon text-primary"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{{ url_for('home.index') }}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('home.index') }}#about"
            >About Us</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('portfolio.portfolios')}}"
            >Portfolio</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('casestudies.case_studies') }}"
            >Casestudies</a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('home.index') }}#reviews"
            >Testimonials</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('blogs.blogs') }}">Blog</a>
        </li>
        <li class="nav-item">
          <div class="admin">
            {% if current_user.is_authenticated %} {% if current_user.is_admin
            %}
            <a
              href="{{ url_for('admin.dashboard') }}"
              class="nav-link admin__btn"
              >Dashboard</a
            >
            {% else %}
            <a href="{{ url_for('users.logout') }}" class="nav-link admin__btn"
              >Logout</a
            >
            {% endif %} {% else %}
            <a href="{{ url_for('users.login') }}" class="nav-link admin__btn"
              >LogIn / <span class="text-warning">signUp</span></a
            >
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% endblock %} {% block scripts %}
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.5.1/tinymce.min.js"
  integrity="sha512-SJh7xW/9SLzllt0PqjnYlomfUPi7UYF40TXU5m6kVXLFr1hdKe+L8Tqqoi1y9vlsMQBdGC2lZI0d6w04Nn6piQ=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>

<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}

app/templates/sweetalerts.html
<!-- Begin alerts -->
{% with messages = get_flashed_messages(with_categories=true) %} 
  {% if messages%} 
    {% for category, message in messages %}
      <script>
        Swal.fire({
          title: "{{ category.title() }}!",
          // success , error , warning ,info

          text: "{{ message }}",
          // Custom message flashed from your flask routes

          icon: "{{ category }}" == "danger" ? "error" : "{{ category }}",
          // success , error , warning ,info
        });
      </script>
    {% endfor %} 
  {% endif %} 
{% endwith %}

<!-- End alerts -->