app/blueprints/portfolios/views.py
from urllib.parse import quote_plus
from flask import current_app, flash, jsonify, url_for, render_template, redirect, request, Blueprint
from flask_login import login_required, current_user
from app.app import db
from werkzeug.utils import secure_filename
from app.utils import allowed_file
from app.models import PartnerMedia, Portfolio, Media
import os


portfolio_blueprint = Blueprint("portfolio", __name__, template_folder='templates')


# --------------------------------------> Start of Portfolio Section <---------------------------------------

@portfolio_blueprint.route('/add_portfolio', methods=['POST'])
@login_required
def add_portfolio():
    try:
        location = request.form['location']
        project_name = request.form['project_name']
        description = request.form['description']
        images = request.files.getlist('image_ids[]')
        
        # Create and add new portfolio
        portfolio = Portfolio(project_name=project_name, location=location, description=description)
        db.session.add(portfolio)
        db.session.commit()
        
        # Add images to the new portfolio
        for image in images:
            if image and allowed_file(image.filename):
                # Save image
                filename = secure_filename(image.filename)
                image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
                image.save(image_path)
                
                # Create Media entry
                media = Media(filename=filename, portfolio_id=portfolio.portfolio_id)
                db.session.add(media)
        
        db.session.commit()
        flash('Portfolio added successfully!', 'success')
        return redirect(url_for('admin.dashboard') + '#portfolio')
    
    except Exception as e:
        flash(f'message {str(e)}', 'success')
        return redirect(url_for('admin.dashboard')  + '#portfolio')


@portfolio_blueprint.route('/edit_portfolio/<int:portfolio_id>', methods=['POST'])
@login_required
def edit_portfolio(portfolio_id):
    if not current_user.is_admin:
        return jsonify({'success': False, 'message': 'Unauthorized access.'}), 403

    portfolio = Portfolio.query.get_or_404(portfolio_id)
    portfolio.project_name = request.form['project_name']
    portfolio.location = request.form['location']
    portfolio.description = request.form['description']

    # Handle deletion of selected images
    delete_image_ids = request.form.getlist('delete_images[]')
    for media_id in delete_image_ids:
        media = Media.query.get(media_id)
        if media:
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], media.filename)
            if os.path.exists(image_path):
                os.remove(image_path)
            db.session.delete(media)

    # Handle uploading new images
    if 'image_ids[]' in request.files:
        images = request.files.getlist('image_ids[]')
        for image in images:
            if image:
                filename = secure_filename(image.filename)
                image.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))
                media = Media(filename=filename, portfolio_id=portfolio.portfolio_id)
                db.session.add(media)

    db.session.commit()

    flash('Portfolio updated successfully!', 'success')
    return redirect(url_for('admin.dashboard') + '#portfolio')


from flask import redirect, url_for, flash

@portfolio_blueprint.route('/delete_image/<int:portfolio_id>/<int:media_id>', methods=['POST'])
@login_required
def delete_portfolio_image(portfolio_id, media_id):
    try:
        if not current_user.is_admin:
            flash('Unauthorized access. Admin access required.', 'error')
            return redirect(url_for('portfolio.portfolios', portfolio_id=portfolio_id))

        # Try to get the media record by ID
        media = Media.query.get_or_404(media_id)

        # Construct the path to the image
        image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], media.filename)

        # Check if the image file exists and remove it
        if os.path.exists(image_path):
            os.remove(image_path)
        else:
            flash('Image file not found on the server.', 'error')
            return redirect(url_for('portfolio.portfolios', portfolio_id=portfolio_id))

        # Delete the media record from the database
        db.session.delete(media)
        db.session.commit()

        flash('Image deleted successfully.', 'success')
        return redirect(url_for('portfolio.portfolios', portfolio_id=portfolio_id))
    
    except Exception as e:
        flash(f'An error occurred: {str(e)}', 'error')
        return redirect(url_for('portfolio.portfolios', portfolio_id=portfolio_id))


@portfolio_blueprint.route('/delete_portfolio/<int:portfolio_id>', methods=['POST'])
@login_required
def delete_portfolio(portfolio_id):
    portfolio = Portfolio.query.get(portfolio_id)
    if not portfolio:
        flash('Portfolio not found!', 'success')

    # Delete associated images
    if hasattr(portfolio, 'media'):
        for image in portfolio.media:
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], image.filename)
            if os.path.exists(image_path):
                os.remove(image_path)
            db.session.delete(image)

    # Delete portfolio
    db.session.delete(portfolio)
    db.session.commit()

    flash('Portfolio deleted successfully!', 'success')
    return redirect(url_for('admin.dashboard')  + '#portfolio')



@portfolio_blueprint.route('/portfolios')
def portfolios():
    portfolios = Portfolio.query.all()
    return render_template('portfolios/portfolios.html', portfolio=portfolios)


# @portfolio_blueprint.route('/portfolio/<string:project_name>')
# def portfolio_details(project_name):
#     portfolio = Portfolio.query.filter_by(project_name=project_name).first_or_404()
#     project_name = quote_plus(portfolio.project_name)
#     return render_template('portfolios/portfolio_details.html', portfolio=portfolio)

import markdown
from flask import render_template, redirect, url_for, flash
from urllib.parse import quote_plus

@portfolio_blueprint.route('/portfolio/<string:project_name>')
def portfolio_details(project_name):
    portfolio = Portfolio.query.filter_by(project_name=project_name).first_or_404()
    project_name = quote_plus(portfolio.project_name)

    # Convert Markdown to HTML with code highlighting support
    portfolio.description = markdown.markdown(
        portfolio.description,
        extensions=["fenced_code", "codehilite"]
    )

    return render_template('portfolios/portfolio_details.html', portfolio=portfolio)

    
# --------------------------------------> End of Portfolio Section <---------------------------------------

app/blueprints/portfolios/templates/portfolios/portfolio_details.html
{% extends "base.html" %} 
{% block head %} 
    {% block title %} 
        Portfolio Page 
    {%endblock %} 
    {% include "sweetalerts.html" %} 
    {% include "others_header.html" %}
    <link rel="stylesheet" href="{{ url_for('static', filename='header.css') }}" />

    <link href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Code highlighter -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
    <script>hljs.highlightAll();</script>

{% endblock %}

{% block content %}
    <style>
        .markdown-content img {
            width: 80%;
            display: block;
        }

        .view-container {
            margin-top: 150px;
        }
    
        .carousel-inner {
            background: var(--background-color);
            border-radius: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2),
                0 6px 20px 0 rgba(0, 0, 0, 0.19);
        }
    
        .carousel-control-prev,
        .carousel-control-next {
            text-decoration: none;
            margin-top: 400px;
            width: 80px;
            height: 80px;
            border-radius: 10%;
            background-color: #333333;
            color: #fff;
            opacity: 0.9;
            transition: opacity 0.3s;
        }
    
        .carousel-control-prev:hover,
        .carousel-control-next:hover {
            opacity: 1;
        }
    
        .carousel-control-prev i,
        .carousel-control-next i {
            font-size: 15px;
        }
    
        p {
            color: #000 !important;
            font-size: 20px !important;
        }

        .admin__btn {
            color: #fff !important;
        }

    </style>

    <section class="view-container">
        <!-- portfolio_details.html -->
    
        <!-- Portfolio Details -->
        <div class="container">
            <!-- Carousel for images -->
            <div id="portfolio-images" class="carousel slide" data-ride="carousel" data-interval="false">
                <div class="carousel-inner">
                    {% if portfolio.media and portfolio.media|length > 0 %} 
                    {% for media in portfolio.media %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img src="{{ url_for('static', filename='uploads/' ~ media.filename) }}" alt="Portfolio Image"
                            class="port-img d-block w-100" />
                    </div>
                    {% endfor %} {% else %}
                    <div class="carousel-item active">
                        <img src="{{ url_for('static', filename='default_image.png') }}" alt="Default Image"
                            class="port-img d-block w-100" />
                    </div>
                    {% endif %}
                </div>
                <a class="carousel-control-prev" href="#portfolio-images" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
                <a class="carousel-control-next" href="#portfolio-images" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                </a>
            </div>
    
            <!-- Portfolio content -->
            <div class="row mb-5">
                <div class="col-lg-12">
                    <h1>{{ portfolio.project_name }}</h1>
                    <h3 class="text-dark">Location: {{ portfolio.location }}</h3>
                    
                    <p class="text-dark">
                        <div class="markdown-content descr-text">
                            {{ portfolio.description | markdown | safe }}
                        </div>
                        
                    </p>
                    
                </div>
            </div>
        </div>
    </section>

{% endblock %}


{% block scripts %}
    <!-- jQuery and Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>

    <!-- Highlight.js initialization -->
    <script>hljs.highlightAll();</script>

    <!-- Open links in new tab -->
    <script>
        document.querySelectorAll('.markdown-content a').forEach(function (anchor) {
            anchor.setAttribute('target', '_blank');
        });
    </script>
{% endblock %}

app/blueprints/portfolios/templates/portfolios/portfolios.html
{% extends "base.html" %} 
{% block head %} 
  {% block title %} 
    Portfolio Page
  {%endblock %} 
  {% include "sweetalerts.html" %} 
  {% include "others_header.html"%}
  <link rel="stylesheet" href="{{ url_for('static', filename='header.css') }}" />

  <!-- Sweet alert Js -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <!-- Bootstrap Links -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  
  <!-- SimpleMDE CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <!-- SimpleMDE JS -->
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

  <!-- JQuery Link -->
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
    crossorigin="anonymous"></script>

  <!-- Bootstrap Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
  <script>
    hljs.highlightAll();
  </script>

{% endblock %} 
{% block content %}

<style>
  .card {
    background: var(--background-color);
    border-radius: 10px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    padding-bottom: 28px;
  }

  .view-container {
    margin-top: 150px;
  }

  .portfolio__container .edit_or_delete {
    display: flex;
    margin-top: 3%;
    margin-left: 8%;
    gap: 10px;
    margin-bottom: 11px !important;
  }

  .portfolio__container .edit_or_delete .edit {
    background: var(--primary-color);
    padding: 5px 20px;
    border-radius: 50%;
    color: var(--background-color);
    cursor: pointer;
  }


  .portfolio__container .edit_or_delete .delete {
    color: var(--background-color);
    padding: 5px 20px;
    border-radius: 50%;
    background: rgb(112, 4, 4);
    cursor: pointer;
  }
</style>

<section class="view-container">
  <div class="container">
    

    <h1 class="text-center">My Portfolios</h1>
    <!-- Portfolio Container -->
    <div class="all_portfolio-container row">
      {% for item in portfolio %}
      <!-- Portfolio Card -->
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <div
          class="card portfolio_card h-100 p-0">
          <div class="card-body portfolio__container p-0">
            <!-- Image -->
            <div class="img__div">
              {% if item.media and item.media|length > 0 %}
              <img
                class="card-img-top"
                src="{{ url_for('static', filename='uploads/' ~ item.media[0].filename) }}"
                alt="{{ item.project_name }}"
              />
              {% else %}
              <img
                src="{{ url_for('static', filename='default_image.png') }}"
                alt="Default Image"
              />
              {% endif %}
            </div>

            <div class="card-body">
              <!-- Details -->
              <ul class="list-unstyled">
                <li>
                  <div class="location-div d-flex">
                    <i class="bi bi-geo-alt text-primary"></i>
                    <p class="card-text location ml-3 text-dark">
                      {{ item.location }}
                    </p>
                  </div>
                </li>
              </ul>
              <a class="text-decoration-none" href="{{ url_for('portfolio.portfolio_details', project_name=item.project_name) }}">
                <h3 class="card-title project__type">{{ item.project_name }}</h3>
              </a>
              
            </div>
              {% if current_user.is_admin%}
              <div class="edit_or_delete">
                <!-- Edit button -->
                <span class="icon edit" data-bs-toggle="modal"
                    data-bs-target="#editPortfolioModal-{{ item.portfolio_id }}">
                    <i class="bi bi-pen"></i>
                </span>

                <!-- Delete button with SweetAlert confirmation -->
                <form id="deletePortfolioForm-{{ item.portfolio_id }}"
                    action="{{ url_for('portfolio.delete_portfolio', portfolio_id=item.portfolio_id) }}" method="POST"
                    style="display:inline;">
                    <button type="button" class="icon delete"
                        onclick="confirmDeletePortfolio('{{ item.portfolio_id }}')">
                        <i class="bi bi-trash"></i>
                    </button>
                </form>
              </div>
              {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

  {% if portfolio %}
    {% for item in portfolio %}
      <!-- Edit Portfolio Modal -->
      <div class="modal fade" id="editPortfolioModal-{{ item.portfolio_id }}" tabindex="-1"
        aria-labelledby="editPortfolioModalLabel-{{ item.portfolio_id }}" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="editPortfolioModalLabel-{{ item.portfolio_id }}">Edit Portfolio</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="{{ url_for('portfolio.edit_portfolio', portfolio_id=item.portfolio_id) }}" method="POST"
                enctype="multipart/form-data">
                <div class="mb-3">
                  <label for="portfolioLocation" class="form-label">Location</label>
                  <input type="text" class="form-control" id="portfolioLocation" name="location" value="{{ item.location }}"
                    required>
                </div>
                <div class="mb-3">
                  <label for="portfolioType" class="form-label">Project Name</label>
                  <input type="text" class="form-control" id="portfolioType" name="project_name"
                    value="{{ item.project_name }}" required>
                </div>
                <div class="mb-3">
                  <label for="portfolioDescription" class="form-label">Description</label>
                  <textarea class="form-control markdown-editor" id="editportfolioDescription" name="description" rows="4"
                    required>{{ item.description }}</textarea>
                </div>
                <div class="mb-3">
                  <label for="portfolioImageInput" class="form-label">Upload New Images</label>
                  <input type="file" class="form-control" id="portfolioImageInput" name="image_ids[]" accept="image/*"
                    multiple>
                </div>
                <div class="mb-3">
                  <label for="existingImages" class="form-label">Existing Images</label>
                  <div id="existingImages">
                    {% for media in item.media %}
                    <div class="existing-image" data-media-id="{{ media.media_id }}">
                      <img src="{{ url_for('static', filename='uploads/' ~ media.filename) }}" alt="Existing Image"
                        class="img-thumbnail" style="max-width: 100px;">
                      <button type="button" class="btn btn-danger btn-sm"
                        onclick="confirmDeletePortfolioImage('{{ item.portfolio_id }}', '{{ media.media_id }}')">Delete</button>
                    </div>
                    {% endfor %}
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
      {% endfor %}
      {% else %}
      <p class="text-center text-danger fs-5">No PortFolio available.</p>
    {% endif %}
</section>
{% endblock %} {% block scripts %}
<script src="{{ url_for('static', filename='js/script.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">

<!-- BOOTSTRAP CDN LINK -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>



<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
<!-- Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>

<script integrity="sha384-MrcW6ZMFYlXZ
          *zcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>


{% endblock %}



<script src="{{ url_for('static', filename='js/script.js') }}"></script>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
  <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
  
  <!-- BOOTSTRAP CDN LINK -->
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
  
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.6/dist/umd/popper.min.js"></script>
  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  
  <script integrity="sha384-MrcW6ZMFYlXZ
            *zcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>